"""Add max_tickets field to flight

Revision ID: b1903b4ba549
Revises: 97c574316548
Create Date: 2025-12-20 19:29:58.401254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1903b4ba549'
down_revision: Union[str, Sequence[str], None] = '97c574316548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('max_tickets', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'max_tickets')
    # ### end Alembic commands ###
