"""Add superuser flags and flight status fields

Revision ID: d0336c6d718e
Revises: 3e185f13fe5b
Create Date: 2025-12-19 12:17:04.589073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0336c6d718e'
down_revision: Union[str, Sequence[str], None] = '3e185f13fe5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('app_user', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.add_column('flight', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'status')
    op.drop_column('app_user', 'is_blocked')
    op.drop_column('app_user', 'is_superuser')
    # ### end Alembic commands ###
