"""Refactor: cleanup unused tables Cargo and Seat

Revision ID: e30ec27f1fa0
Revises: 2fb8128ddbb9
Create Date: 2025-12-24 02:21:23.708261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30ec27f1fa0'
down_revision: Union[str, Sequence[str], None] = '2fb8128ddbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ticket_seat_id_fkey'), 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'seat_id')
    op.drop_table('seat')
    op.drop_table('cargo')
    op.drop_table('seat_type')
    op.drop_table('cargo_type')
    op.drop_table('transport_feature')
    #op.drop_constraint(op.f('uq_flight_seat_ticket'), 'ticket', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('seat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('ticket_seat_id_fkey'), 'ticket', 'seat', ['seat_id'], ['id'])
    op.create_unique_constraint(op.f('uq_flight_seat_ticket'), 'ticket', ['flight_id', 'seat_id'], postgresql_nulls_not_distinct=False)
    op.create_table('cargo_type',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cargo_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('cargo_type_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cargo_type_pkey'),
    sa.UniqueConstraint('cargo_type_name', name='cargo_type_cargo_type_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('cargo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mass', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('cargo_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transport_feature_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passenger_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('flight_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cargo_type_id'], ['cargo_type.id'], name=op.f('cargo_cargo_type_id_fkey')),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], name=op.f('cargo_flight_id_fkey')),
    sa.ForeignKeyConstraint(['passenger_id'], ['passenger.id'], name=op.f('cargo_passenger_id_fkey')),
    sa.ForeignKeyConstraint(['transport_feature_id'], ['transport_feature.id'], name=op.f('cargo_transport_feature_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cargo_pkey'))
    )
    op.create_table('seat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seat_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('seat_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aircraft_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], name=op.f('seat_aircraft_id_fkey')),
    sa.ForeignKeyConstraint(['seat_type_id'], ['seat_type.id'], name=op.f('seat_seat_type_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('seat_pkey'))
    )
    op.create_table('transport_feature',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('transport_feature_pkey')),
    sa.UniqueConstraint('feature_name', name=op.f('transport_feature_feature_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('seat_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seat_type_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('seat_type_pkey')),
    sa.UniqueConstraint('seat_type_name', name=op.f('seat_type_seat_type_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
